Repository wechatpy/wechatpy, pull requests merged in 2018-03, with the labels that each got.

#345 增加对沙盒支付的支持、针对不同前端的支持
  wechatpy/pay/api/jsapi.py
Labels: T: 微信支付, feature, 主动调用

#337 三方平台增加parse_message 处理消息，token cache 在处理消息时自动处理
  wechatpy/client/__init__.py
  wechatpy/component.py
Labels: T: 第三方平台, enhancement, 主动调用

#346 根据微信商铺API手册V1.16新增部分方法
  wechatpy/client/api/merchant/__init__.py
Labels: feature, 主动调用

#349 群发接口增加 send_ignore_reprint 和 client_msg_id 参数
  setup.cfg
  wechatpy/client/api/message.py
Labels: T: 消息管理, feature, 主动调用
