Repository wechatpy/wechatpy, pull requests merged in 2020-03, with the labels that each got.

#523 实现企业微信的日历、日程管理接口
  docs/enterprise/client.rst
  wechatpy/enterprise/client/__init__.py
  wechatpy/enterprise/client/api/__init__.py
  wechatpy/enterprise/client/api/calendar.py
  wechatpy/enterprise/client/api/schedule.py
Labels: 企业微信

#511 增加小程序云调用 API
  README.md
  wechatpy/client/__init__.py
  wechatpy/client/api/__init__.py
  wechatpy/client/api/cloud.py
  wechatpy/client/api/wxa.py
Labels: T: 小程序, help wanted, 主动调用

#535 群发消息接口参数调整
  tests/test_client.py
  wechatpy/client/api/message.py
Labels: Breaking Changes, T: 消息管理, 主动调用

#537 Remove deprecated APIs
  tests/fixtures/component/_sns_oauth2_component_access_token.json
  tests/fixtures/component/_sns_oauth2_component_refresh_token.json
  tests/fixtures/component/_sns_userinfo.json
  tests/fixtures/component/api_component_token.json
  tests/fixtures/enterprise/batch_inviteuser.json
  tests/test_component_api.py
  tests/test_enterprise_client.py
  tests/test_oauth.py
  wechatpy/component.py
  wechatpy/enterprise/client/api/appchat.py
  wechatpy/enterprise/client/api/batch.py
Labels: Breaking Changes

#546 Re-enable Codecov for PR
  .github/workflows/CI.yml
Labels: enhancement

#547 移除企业微信废弃的会话、摇一摇周边接口
  docs/work/client.rst
  tests/fixtures/work/chat_clearnotify.json
  tests/fixtures/work/chat_create.json
  tests/fixtures/work/chat_get.json
  tests/fixtures/work/chat_quit.json
  tests/fixtures/work/chat_send.json
  tests/fixtures/work/chat_setmute.json
  tests/fixtures/work/chat_update.json
  tests/fixtures/work/shakearound_getshakeinfo.json
  tests/test_work_client.py
  wechatpy/work/client/__init__.py
  wechatpy/work/client/api/__init__.py
  wechatpy/work/client/api/chat.py
  wechatpy/work/client/api/shakearound.py
Labels: Breaking Changes, 企业微信

#548 移除企业微信废弃的永久素材接口
  docs/work/client.rst
  tests/fixtures/work/material_batchget.json
  tests/fixtures/work/material_del.json
  tests/fixtures/work/material_get.json
  tests/fixtures/work/material_get_count.json
  tests/test_work_client.py
  wechatpy/work/client/__init__.py
  wechatpy/work/client/api/__init__.py
  wechatpy/work/client/api/material.py
Labels: Breaking Changes, 企业微信

#551 更新接口文档链接
  docs/index.rst
  wechatpy/client/__init__.py
  wechatpy/constants.py
  wechatpy/events.py
  wechatpy/messages.py
  wechatpy/replies.py
Labels: 文档
