Repository wechatpy/wechatpy, pull requests merged in 2020-04, with the labels that each got.

#558 Drop Python 3.5 support
  .github/workflows/CI.yml
  docs/install.rst
  poetry.lock
  pyproject.toml
  wechatpy/pay/api/order.py
  wechatpy/work/client/api/user.py
Labels: Breaking Changes

#563 所有消息类型都整理到 messages.py
  wechatpy/component.py
  wechatpy/messages.py
Labels: refactor

#565 body解析编码使用 utf-8-sig
  wechatpy/pay/__init__.py
Labels: T: 微信支付, enhancement

#567 Cleanup schemes
  poetry.lock
  tests/test_client.py
  wechatpy/client/api/jsapi.py
  wechatpy/schemes.py
Labels: enhancement

#569 refactor: 使用 f-string 格式化字符串 (#568)
  examples/echo-encrypted/app.py
  tests/test_client.py
  tests/test_component_api.py
  tests/test_external_contact.py
  tests/test_fields.py
  tests/test_oauth.py
  tests/test_payment.py
  tests/test_replies.py
  tests/test_send_messages.py
  tests/test_session.py
  tests/test_work_client.py
  wechatpy/client/__init__.py
  wechatpy/client/api/card.py
  wechatpy/client/api/customservice.py
  wechatpy/client/api/device.py
  wechatpy/client/api/jsapi.py
  wechatpy/client/api/media.py
  wechatpy/client/api/message.py
  wechatpy/client/api/qrcode.py
  wechatpy/client/base.py
  wechatpy/component.py
  wechatpy/exceptions.py
  wechatpy/fields.py
  wechatpy/messages.py
  wechatpy/oauth.py
  wechatpy/parser.py
  wechatpy/pay/__init__.py
  wechatpy/pay/api/coupon.py
  wechatpy/pay/api/jsapi.py
  wechatpy/pay/api/micropay.py
  wechatpy/pay/api/order.py
  wechatpy/pay/api/redpack.py
  wechatpy/pay/api/transfer.py
  wechatpy/pay/api/withhold.py
  wechatpy/pay/utils.py
  wechatpy/replies.py
  wechatpy/session/memcachedstorage.py
  wechatpy/session/redisstorage.py
  wechatpy/session/shovestorage.py
  wechatpy/work/client/__init__.py
  wechatpy/work/client/api/appchat.py
  wechatpy/work/client/api/jsapi.py
  wechatpy/work/replies.py
Labels: refactor

#571 确保 fetch_access_token 是方法
  tests/test_client.py
  tests/test_component_api.py
Labels: enhancement, 主动调用

#572 Remove Shove session storage support
  docs/work/quickstart.rst
  poetry.lock
  pyproject.toml
  tests/test_session.py
  wechatpy/client/base.py
  wechatpy/component.py
  wechatpy/session/shovestorage.py
  wechatpy/utils.py
Labels: Breaking Changes
